# Generated by Django 3.1.5 on 2021-01-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, verbose_name='Название клуба')),
                ('country', models.CharField(max_length=25, verbose_name='Страна')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'клуб',
                'verbose_name_plural': 'клубы',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=40, verbose_name='Название турнира')),
                ('year_held', models.IntegerField(verbose_name='Год проведения')),
                ('country_name', models.CharField(default='', max_length=25, verbose_name='Место проведения')),
                ('is_regular', models.BooleanField(default=True, verbose_name='Регулярный сезон')),
                ('teams_participant', models.ManyToManyField(to='sportstats.Team', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'турнир',
                'verbose_name_plural': 'турниры',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_held', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('first_team_scores', models.IntegerField(verbose_name='Голы (хозяева)')),
                ('second_team_scores', models.IntegerField(verbose_name='Голы (гости)')),
                ('first_team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='sportstats.team', verbose_name='Хозяева')),
                ('second_team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='sportstats.team', verbose_name='Гости')),
                ('tournament_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportstats.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'матч',
                'verbose_name_plural': 'матчи',
            },
        ),
    ]
