# Generated by Django 3.1.5 on 2021-01-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportstats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='first_team_name',
            new_name='first_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='second_team_name',
            new_name='second_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='tournament_name',
            new_name='tournament',
        ),
    ]
